"""Add cv_events_json and highlights_s3_key to jobs for pose analysis results.

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-07

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Store CV-detected events (shots, rebounds, steals) as structured JSON on the job
    op.add_column(
        "jobs",
        sa.Column("cv_events_json", postgresql.JSONB(), nullable=True),
    )
    # S3 key for the highlights reel video generated by HighlightGenerator
    op.add_column(
        "jobs",
        sa.Column("highlights_s3_key", sa.String(500), nullable=True),
    )
    # S3 key for the highlights clips manifest (JSON list of individual clip metadata)
    op.add_column(
        "jobs",
        sa.Column("highlights_manifest_key", sa.String(500), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("jobs", "highlights_manifest_key")
    op.drop_column("jobs", "highlights_s3_key")
    op.drop_column("jobs", "cv_events_json")
