"""Scouting report models generated by LLM."""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..core.types import JsonB

from ..core.database import Base


class ScoutingReport(Base):
    __tablename__ = "scouting_reports"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    matchup_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("matchups.id", ondelete="CASCADE"), index=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    model_used: Mapped[str | None] = mapped_column(String(100))
    team_identity: Mapped[str | None] = mapped_column(Text)
    strengths: Mapped[list | None] = mapped_column(JsonB)
    weaknesses: Mapped[list | None] = mapped_column(JsonB)
    mvp_players: Mapped[list | None] = mapped_column(JsonB)
    game_keys_offensive: Mapped[list | None] = mapped_column(JsonB)
    game_keys_defensive: Mapped[list | None] = mapped_column(JsonB)
    coach_notes: Mapped[str | None] = mapped_column(Text)
    box_scores_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    matchup: Mapped["Matchup"] = relationship(back_populates="scouting_reports")
    player_notes: Mapped[list["PlayerScoutingNote"]] = relationship(back_populates="report")


class PlayerScoutingNote(Base):
    __tablename__ = "player_scouting_notes"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("scouting_reports.id", ondelete="CASCADE"), index=True
    )
    player_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("players.id", ondelete="SET NULL"), nullable=True
    )
    player_name: Mapped[str | None] = mapped_column(String(255))
    summary: Mapped[str | None] = mapped_column(Text)
    is_mvp: Mapped[bool] = mapped_column(Boolean, default=False)
    mvp_rank: Mapped[int | None] = mapped_column(Integer)

    report: Mapped["ScoutingReport"] = relationship(back_populates="player_notes")
